# Generated by Django 3.2.4 on 2021-06-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musixbox', '0002_alter_musicians_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbums',
            name='genre',
            field=models.CharField(choices=[('1', 'Instrumental'), ('2', 'Classical'), ('3', 'POP'), ('4', 'Rock'), ('5', 'Western')], max_length=30),
        ),
    ]
