# Generated by Django 3.2.4 on 2021-06-23 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musixbox', '0003_alter_musicalbums_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbums',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
